sudo: false
language: node_js
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/

stages:
  - lint
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: lint
      script: npm run jshint
    - stage: test
      node_js: 6
      script: test-node
    - node_js: 8
      script: test-node
    - node_js: 10
      script: test-node
    - node_js: lts/*
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script: CLIENT=saucelabs:firefox npm run test-browser
    - stage: release
      script: npm run semantic-release
