sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: CLIENT=saucelabs:firefox npm test
after_success:
  - npm run semantic-release
